### PR TITLE
#87: Attempt to fix Java 8 method reference reload

### PR DESCRIPTION
**Pull request by ilx**
Please forgive me changes introduced by formatter.

### CODE REVIEW

**Comment by aclement** [comment]
Do your changes pass all the tests? I tried them and I see 2 failures - 2 of the 3 new tests I added yesterday for issue 87 (the tests proposed at the top of the bug)? Could be worth writing some other tests for more scenarios too, I know what we have isn't sufficient.

**Comment by ilx** [comment]
I have noticed that TestJava8#lambdaInvokeVirtual is failing so I took another bite and found one more potential issue. 

Instead of trying to figure out what's wrong from test perspective I have created a sample eclipse project with 2 source folders. One containing original version of LambdaJ:

```java
package basic;

public class LambdaJ {

    public interface Foo { String m(String s); }

    public String getFoo(String s)  {
        System.out.println("in first foo");
        return "foo"+s;
    }

    public static void main(String[] args) {
        run();// put breakpoint
        run();
    }

    public static String run() {
        return new LambdaJ().run2();
    }

    public String run2() {
        Foo f = this::getFoo;
        return f.m("a");
    }
}
```

and the second source folder (initially disabled) has modifications that I believe match LambdaJ2:

```java
public class LambdaJ {

    public interface Foo {
        String m(String s, String s2);
    }

    public String getFoo(String s, String s2) {
        System.err.println("in second foo");
        return "foo" + s + s2;
    }

    public LambdaJ() {
        System.err.println("modified instance");
    }

    public static void main(String[] args) {
        run();
        run();
    }

    public static String run() {
        String res = new LambdaJ().run2();
        System.err.println(res);
        return res;
    }

    public String run2() {
        Foo f = this::getFoo;
        return f.m("a", "b");
    }

}
```

I have executed this using following eclipse run configuration:
```
-noverify
-Dspringloaded=logging=true;verbose=true;verbose
-Djava.util.logging.config.file=${project_path:/springloaded/logging.properties}
-javaagent:${resource_loc:/springloaded/build/libs/springloaded-1.2.2.BUILD-SNAPSHOT.jar}
```

In the middle of execution (after first run is executed) I've put breakpoint, disabled initial source folder and enable second one. Spring loaded kicks in and I have a debug environment.

Since test failed I found that there are actually 2 methods available and assumptions in iiIntercept are wrong: 

```java
    public static Object iiIntercept(Object instance, Object[] params, Object instance2, String nameAndDescriptor) {
        Class<?> clazz= instance.getClass();
        try {
            if (clazz.getName().contains("$$Lambda")) {
                // There will only be one method, the SAM method
                // =====> Actually there may be more than one method and we will use last one defined
                // for an example see LambdaJ getFoo
                // first method instance is private static basic.LambdaJ$Foo basic.LambdaJ$$EP6YMM3E$$Lambda$2/1014328909.get$Lambda(basic.LambdaJ)
                // the second method instance is public java.lang.String basic.LambdaJ$$EP6YMM3E$$Lambda$2/1014328909.m(java.lang.String,java.lang.String)
                Method[] ms = instance.getClass().getDeclaredMethods();
                Method m = ms[ms.length-1]; // was 0
                m.setAccessible(true);
                Object o = m.invoke(instance, params);
                return o;
            }
            else {
                // Do what you were going to do...
                Method m = instance.getClass().getDeclaredMethod("__execute",Object[].class,Object.class,String.class);
                m.setAccessible(true);
                return m.invoke(instance, params, instance, nameAndDescriptor);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

```

I couldn't figure out how to automate this on my own (ReloadingJVM just doesn't capture sysout on oracle jdk8 on linux) so I would appreciate your help.

What I would like to do in SpringLoadedTestsInSeparateJVM (compilation actually works, the test fails because there's no output captured): 

```java
    private String[] copyToCompileFolder(File compileFolder, String prefix, String... files) throws IOException {
        List<String> sourceFiles = new ArrayList<String>();
        for (String name: files) {
            InputStream is = this.getClass().getResourceAsStream(name);
            String destName = name.replace(".file", "");
            destName = destName.replace(prefix, "");
            Path destPath = new File(compileFolder, destName).toPath();
            destPath.toFile().mkdirs();
            Files.copy(is, destPath, StandardCopyOption.REPLACE_EXISTING);
            sourceFiles.add(destPath.toFile().getPath());
        }
        return sourceFiles.toArray(new String[sourceFiles.size()]);
    }

    public void compile(File compileFolder,String... files) throws IOException {
        System.out.println(compileFolder.toString());
        JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
        compiler.run(null, null, null, files);
    }

    public void compile(String prefix, String files) throws IOException {
        File compileDir = jvm.testdataDirectory;
        String[] copiedFiles = copyToCompileFolder(compileDir, prefix, files);
        compile(compileDir, copiedFiles);
    }


    @Test
    public void testLambdaJ() throws IOException {
        compile("/original/", "/original/basic/LambdaJ.java.file");
        JVMOutput output = jvm.sendAndReceive("run basic.LambdaJ");

        assertStdoutContains("in first foo", output); // nothing... 
        assertStdoutContains("fooa", output);
        compile("/modified/", "/modified/basic/LambdaJ.java.file");

        jvm.reload("basic.LambdaJ"); // is this enough?

        output = jvm.sendAndReceive("run basic.LambdaJ");
        assertStdoutContains("in second foo", output);
        assertStdoutContains("fooa2", output);
        output = jvm.sendAndReceive("exit");
    }

```


P.S. Can you share your eclipse formatter settings? I would like to reduce number of changes. Do you develop on windows?

**Comment by ilx** [comment]
I have updated PR, this time all of the tests are passing. I have also created 2 new test for method references.

**Comment by aclement** [comment]
I'm afraid that PR is just too much change for me to sort through. Can you not configure your setup to avoid formatting lines you aren't actually changing?  I'm on a mac and my current eclipse is not using any custom format rules, just set to defaults. The eclipse I originally used when writing the code, well it might have had some rules in it but that is long gone. We probably should have a set of rules committed to the repo, but at the moment we don't unfortunately. (probably the standard spring rules should be used). Thanks for taking the time to dig into the issue!

**Comment by ilx** [comment]
I'm afraid I don't have enough willpower to push this formatting hell any further. 
You may decide to make those changes manually. 

in TypeRegistry:
```
public static Object iiIntercept(Object instance, Object[] params, Object instance2, String nameAndDescriptor) {
		Class<?> clazz = instance.getClass();
		try {
			if (clazz.getName().contains("$$Lambda")) {
				// There will only be one method, the SAM method
				// Actually there may be more than one method and we will use last one defined
				// for an example see LambdaJ getFoo
				// first instance is private static basic.LambdaJ$Foo basic.LambdaJ$$EP6YMM3E$$Lambda$2/1014328909.get$Lambda(basic.LambdaJ)
				// the second instance is public java.lang.String basic.LambdaJ$$EP6YMM3E$$Lambda$2/1014328909.m(java.lang.String,java.lang.String)
				Method[] ms = instance.getClass().getDeclaredMethods();
				Method m = ms[ms.length - 1]; // was 0
				m.setAccessible(true);
				Object o = m.invoke(instance, params);
				return o;
			} else {
				// Do what you were going to do...
				Method m = instance.getClass().getDeclaredMethod("__execute", Object[].class, Object.class, String.class);
				m.setAccessible(true);
				return m.invoke(instance, params, instance, nameAndDescriptor);
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		return null;
	}
```

in Java8:
```
		case Opcodes.H_INVOKEVIRTUAL:
			// If there is an executor, the lambda function is actually modified from 'private instance' to 'public static' so adjust lookup. The method
			// will be static with a new leading parameter.
			// TODO when can this scenario occur? Aren't we only here if reloading has happened?
			// A: when we're about to invoke reference method from a class that wasn't rewritten
			// say we have a rest service AccountResource that invokes Authority::getName()
			// if we change Authority, executorClass will be null, AccountResource is not reloaded yet,
			// and we need to invoke getName on rewritten Authority
			TypeRegistry typeRegistry = rtype.getTypeRegistry();
			int ownerTypeId = typeRegistry.getTypeIdFor(owner, false);
			ReloadableType ownerReloadableType = typeRegistry.getReloadableType(ownerTypeId);
			if (null != ownerReloadableType) {
				MethodMember currentMethod = ownerReloadableType.getCurrentMethod(name, descriptor);
				CurrentLiveVersion liveVersion = ownerReloadableType.getLiveVersion();
				if (null != liveVersion) {
					Class<?> ownerExecutorClass = liveVersion.getExecutorClass();
					Method executorMethod = liveVersion.getExecutorMethod(currentMethod);
					String methodDescriptor = Type.getType(executorMethod).getDescriptor();
					MethodType type = MethodType.fromMethodDescriptorString(methodDescriptor, callerLoader);
					implMethod = caller.findStatic(ownerExecutorClass, name, type);

					// if we change something in the class that caller references then caller has to update it's reference
					// I don't know if this is the best way to do it
					if (!rtype.hasBeenReloaded()) {
						rtype.simulateReload();
					}
				} else {
					// AccountResource uses method reference to Authority::getName()
					// and we made a change only in AccountResource
					Class<?> refc = ownerReloadableType.getClazz();
					implMethod = caller.findVirtual(refc, name, implMethodType);
				}
			} else {
				// IMPORTANT: don't know where this happens so I'm leaving it for backwards (in)compatibility
				implMethod = caller.findVirtual(caller.lookupClass(), name, implMethodType);
			}
			break;
```

other changes are related to tests - if you want to you may later take fixes for ReloadingJVM and ReloadingJVMCommandProcess. I've setup 2 sample tests that take original file, compile it, execute run, verify, take modified file, compile it, reload, execute run, verify...

**Comment by aclement** [comment]
I tried applying just those two changes. The test Java8.lambdaInvokeVirtual() fails. I then tried applying just the second part (Java8 changes) and the test succeeds, so I think (with respect to the iiIntercept changes) on your setup it is correct to choose the 'last method' in iiIntercept but on mine it is correct to always choose the 'first method' - so I guess more smarts is required in that block to make the right choice regardless of return order.

**Comment by aclement** [comment]
I tweaked the TypeRegistry change to use the first public method it finds, which is *probably* what we want.

**Comment by ilx** [comment]
Thanks Andrew. I closed this PR by accident, please close it when you think it should be closed.

**Comment by aclement** [comment]
I've taken what I can - grabbed the tests, added some extra ones. I spent a lot of time looking at that bit of code:

                 if (!rtype.hasBeenReloaded()) {
                        rtype.simulateReload();
                 }

In the end I reworked the changes to avoid the need to try and do that, it seemed even if you did do a simulate of the reload you would still get a single failure because that reload won't take affect until this invokedynamic is done. Thanks so much for the assistance on this.

**Pull request closed without merging**
